version: '3'
services:
    nginx:
        ports:
            - '80:80'
    taking-dictionary:
        build:
            context: .
            args:
                NODE_ENV: production
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=production
        command: node index.js
