version: '3'
services:
    nginx:
        ports:
            - '5000:80'
    taking-dictionary:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - MONGO_USER=santosh
            - MONGO_PASSWORD=mypass
            - TOKEN_SECRET=thisissecrettokenkeydfsdfadadsecret
        command: npm run dev

    mongo:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=santosh
            - MONGO_INITDB_ROOT_PASSWORD=mypass
