version: '3'
services:
    taking-dictionary:
        build: .
        ports:
            - '5000:5000'
        environment:
            - PORT=5000
        depends_on:
            - mongo

    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=santosh
            - MONGO_INITDB_ROOT_PASSWORD=mypass
        volumes:
            - mongo-db:/data/db

volumes:
    mongo-db:
