version: '3'
services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - '5000:80'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    taking-dictionary:
        build: .

        environment:
            - PORT=5000
        depends_on:
            - mongo

    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=santosh
            - MONGO_INITDB_ROOT_PASSWORD=mypass
        volumes:
            - mongo-db:/data/db

volumes:
    mongo-db:
